# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adfa5b6bb4625c48fb63189075eb7d5b32a9690a37a44ee7b52365b7e9447f21b5dcd9f028598772649000e5077f3983ddb93fb2562477fd3fbac50d3287e7bb

test:
  secret_key_base: 2d555eda5ea1dae9d15d81ce6a05a4fd910eca2824e0a7a5a8a3e41c60f83c966d96254afbd402214192c50216bf771ace3b93dd68b4e24d203686bde7463e2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
